
import AuthProvider from '@/providers/AuthProvider'
import '@radix-ui/themes/styles.css';
import './globals.css'
import type { Metadata } from 'next'
import { Theme, ThemePanel } from '@radix-ui/themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Theme>
          <AuthProvider>{children}</AuthProvider>
           {/* <ThemePanel /> */}
        </Theme>
        </body>
    </html>
  )
}
